trigger:
  batch: true
  branches:
    include:
      - 'main'
  paths:
    exclude:
      - README.md

name: SQL_Collector_$(BuildDefinitionName)_$(Build.SourceBranchName)_$(Date:yyyyMMdd).$(Rev:rr)

stages:
- template: /pipelines/stage_templates/setup.yml
  parameters:
    targetEnvironment: 'Prod'
    buildConfiguration: 'release'
    azServiceConnection: 'SQLCollectorSHA-UAMI'

- stage: build
  jobs:
  - template: /pipelines/job_templates/build.yml
    parameters:
      parameters.preBuildSteps: []
      buildConfiguration: 'release'
 
- template: /pipelines/stage_templates/deployFunction.yml
  parameters:
    azServiceConnection: 'SQLCollectorSHA-UAMI'
    functionAppName: 'sqlcollector-prod-fa'
    targetSqlCollectorDb: 'sqlcollector-prod-sqlsvr.database.windows.net'

- stage: configure
  dependsOn: deploy
  jobs:
  - job: deploy_staging
    pool:
      name: 'SQL Collector Self Hosted'
    steps:
    - script: echo Staging
